AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'public/**/*'
Metrics/LineLength:
  Enabled: true
  Max: 120
Metrics/BlockLength:
  Enabled: true
  Max: 40
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/WordArray:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
