version: 2
jobs:
  build:
    working_directory: ~/chisinau_air
    docker:
      - image: circleci/ruby:2.6
        environment:
          RAILS_ENV: test
      - image: mongo:3.4-xenial
    steps:
      - checkout

      - run: bundle exec rubocop

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: chisinau_air-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: chisinau_air-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
